### ISSUE TITLE
Releasing 2.0.0

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#267]
We are in the last week or so before the official 2.0.0 release 🎉 

Closing #234 and moving the leftover issues here for cleanliness 👍 

Fixed bugs:
- [x] Windows installer needs to be < 100MB. Was including all versions of _ffmpeg_. Fixed with #268 
- [x] Since I added i18n to System messages, the build didn't run after installation. Fixed with #268
- [x] If you don't touch settings, VHA extracts 3 thumbs per filmstrip #272; fixed with https://github.com/whyboris/Video-Hub-App/commit/8adc27a63624a0f26005e613127f11bac9e41eac 
- [x] Creating hub from the root of an external hard drive might not display icons: https://github.com/whyboris/Video-Hub-App/issues/270#issuecomment-526868224
- [x] Sorting by duration, file size, etc results in mismatch between clicked and opened video; fixed with #274 
- [x] Add code to close the app gracefully on computer shut down [API](https://electronjs.org/docs/api/power-monitor); fixed with #275 
- [x] VHA will not prevent the computer from going to sleep when extracting 😅 fix with [API](https://electronjs.org/docs/api/power-save-blocker); fixed with #275 

Last steps:
- [x] Make VHA handle corrupt and unfinished download videos #269 
- [x] Wait for _Electron_ to get patched: #260 
- [x] Create new icons: #114 
- [x] Run spell checker on `en.ts` before creating translations!
- [x] Language updates: confirm all the text is understandable, 
- [x] Create all translations #151 
- [x] Get a successful _Windows_ build
- [x] Get a successful _Mac_ build
- [x] Make sure v1 and v2 can live side by side without interfering

**Comment by whyboris** [comment]
#269 - super huge refactor of _extract-screenshots_ functionality 😅 

- should give enough time to extract each thumb/strip/clip/clip thumb
- should not get hung up on corrupt files (there's now a timeout which kills ffmpeg if it takes too long)

**Comment by whyboris** [comment]
Huge thank you to people working on Electron for swiftly releasing a patch, unblocking this release 🙇 
https://github.com/whyboris/Video-Hub-App/issues/260

**Comment by JayVem** [comment]
hi boris, is the new release happening soon?

**Comment by whyboris** [comment]
Thank you for checking in -- I'm busy finishing up a charity-related project this and next week; I hope to release Video Hub App by November 1st now 😅 

Thanks to everyone for your patience 🙇

**Comment by JayVem** [comment]
thank you, appreciate your quick response. Looking forward to the new release.

**Comment by krisu5** [comment]
BTW, do you have to buy another license when it's released? Terms said that updates for a year, but this update has taken over a year, so...

I'm mostly okay with it, just curious.

**Comment by whyboris** [comment]
😓 finally finished the damn icons: https://github.com/whyboris/Video-Hub-App/pull/283 😠  -- making icons is no fun for me

**Comment by whyboris** [comment]
⚠️ At this point I'm soliciting bug reports before the final release -- I'm hoping to get a final build this weekend 🙇 would appreciate any kind of comments too 🙇 

I'm aware of 2 major bugs:
- Creating hub from the root of an external hard drive might not display icons: https://github.com/whyboris/Video-Hub-App/issues/270#issuecomment-526868224
- On some computers as much as 10-15% of videos never thumbnails created https://github.com/whyboris/Video-Hub-App/pull/269#issuecomment-538661367

**Comment by whyboris** [comment]
Moved some minor (non critical) tasks to #284 - for after release. Let's get this release out 🚀 😆

**Comment by whyboris** [comment]
I think I fixed the path issues, closing another bug 🎉 with #286

**Comment by whyboris** [comment]
🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀 
Let's release 🤞

**Comment by whyboris** [comment]
🛑 Nope 😅 
Turns out this bug is not fixed: https://github.com/whyboris/Video-Hub-App/issues/270#issuecomment-526868224

When you import the root of an external hard drive and try to navigate using the _folder_ navigation, folders show up as empty when clicking inside them 😢 

Will fix 👌 ... release delayed until next weekend 🐌

**Comment by LordJon** [comment]
I hope I'm not cluttering the overview here but I just wanted to say this. I've been lurking around and following changes here and on the fixes made for Electron and such. It all sounds very organised. Compliments to all of you.

Also good luck with the last fixes and the backlog for after release. Looking forward for 2.0! 😃

**Comment by whyboris** [comment]
🏷 #287 may have fixed the last major bug with the current release. I'm pretty sure I can release as is (though don't have time until the weekend)

@cal2195 if you are able to, by mid-weekend let me know what happened with https://github.com/whyboris/Video-Hub-App/pull/269#issuecomment-538661367 -- maybe I can fix that up as well before release 🙇 

No worries if you're unable 👌

**Comment by whyboris** [comment]
Cal responded: https://github.com/whyboris/Video-Hub-App/pull/269#issuecomment-542155173

Seems like on the videos above 1080p the timeout is not long enough and the _filmstrip_ extraction process doesn't finish.

So `setExtractionDurations` method that where I roughly guessed about timeout durations should be changed. Specifically, the `filmstrip` computation:

https://github.com/whyboris/Video-Hub-App/blob/master/main-extract.ts#L451

I used a computation taking thumbnail height as a factor in a linear rather than square fashion - a simplification that seems to backfire at higher resolutions. Should be a straightforward fix 👌

**Comment by whyboris** [comment]
Before `2.0.0` release it may be worth replacing the complicated _pipe_ that inserts the `›` icon with the [character](https://graphemica.com/›) `›` 🎉 

This will allow me to remove the leftover font from a while back, and remove the _pipe_ -- will speed things up in the app (an imperceptible amount 😅 )

**Comment by whyboris** [comment]
I updated the method that provides timeouts for killing _ffmpeg_ when extracting takes too long:
https://github.com/whyboris/Video-Hub-App/pull/288/commits/0cd073d88ac9be74eb32912ca901aab4ddd48e69
⚠️ I'm not happy about how I'm handling it, but it's likely better than before 🤷‍♂

**Comment by whyboris** [comment]
Released 😂

**Comment by LordJon** [comment]
Hi Boris, that was fast. Going to test the new 2.0 hub later today. I can't wait. Just a small note, you're blog says that on October the 12th VHA 2.0 was released, probably the previous release date you had in mind before the external drive problem appeared haha.
Cheers!

**Comment by whyboris** [comment]
Thank you @LordJon -- I did forget to update the date on the [Blog](https://videohubapp.com/blog.html) 😅 

I don't feel like I've 100% polished the app, but at this time I think it's safe to release and will take only a little patching up to make it as excellent as I'd like it to be.

Really looking forward to all the feedback 👍
