### ISSUE TITLE
Backlog

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#284]
After version `2.0.0` release:

### Done
- [x] Create a _portable_ Windows installation
- [x] On some computers as many as 10-15% of videos fail extraction: https://github.com/whyboris/Video-Hub-App/pull/269#issuecomment-538661367 
    - fixed with https://github.com/whyboris/Video-Hub-App/commit/0cd073d88ac9be74eb32912ca901aab4ddd48e69
- [x] Clean up path issues `/` vs `\`
- [x] Get a successful _Linux_ build 😅 #218
- [x] Move [this interface](https://github.com/whyboris/Video-Hub-App/blob/acb98f71c9d89ae01cbd8a812f51b6673076b003/main-globals.ts#L36) to [this file](https://github.com/whyboris/Video-Hub-App/blob/master/interfaces/final-object.interface.ts#L6) inside interface folder #323 
- [x] Show full path to video file in the sheet view (with a button to copy path to clipboard maybe) #323 
    - a user requested this feature via email 
- [x] Handle screenshot generation timeout better 🤔 Issue: #295 Fix: #325
- [x] Upgrade to Electron 7 🚀  
- [x] Upgrade to Electron 8 🚀  
- [x] Update to Angular 9 🚀

Unfinished stuff moved to #284 

Other ideas welcome.

**Comment by whyboris** [comment]
Creating a `portable` version is as easy as adding `"portable"` to the `win.target` array in _electron-builder.json_ ... so I'll likely release it along with version 2.0.0 :octocat:

**Comment by whyboris** [comment]
Closing; all unfinished moved to #284
