### ISSUE TITLE
Video Hub App 3

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#456]
I'm working on the next major release of **Video Hub App** version `3.0.0` 🎉 

The intended release date is "when it's ready" 😅 -- probably in a few months once I'm done adding the features, polishing UI, and making sure no bugs are around.

The large bulk of changes to the extraction functionality came in through #443 ✅ 

Two key features:
- More than one 'root' folder per hub 🎉 
- Monitoring of folders (auto update hub when folder changes) courtesy of @cal2195 🙇 

This will be a _breaking change_: 
- v2 hubs will open in version 3 without a problem
- v3 hubs will open in version 2 but with limited functionality (not recommended)

I intend to keep `.vha2` file name (rather than create `.vha3` file name -- though I'm open to a discussion.

Various `TODO` are sprinkled across comments below. Additionally, a short list here:
- [x] make the installed app size smaller #513
- [x] check defaults for `settingsButtons` (whether hidden and/or toggled)
- [x] check keyboard shortcuts (whether need changing and or grouping)
- [x] check button grouping (maybe rearrange order inside the settings tabs)
- [x] create a "welcome" tutorial to show on first app start
- [x] check renaming works from modal, meta, and details views
- [x] update all missing translations for all languages #583 
- [ ] make sure double-click opens app with no errors #546 
- [x] create new VHA website (with _Gatsby_) 🚀 - done: https://github.com/whyboris/video-hub-app-gatsby-website

Feedback and ideas welcome 🤝

**Comment by whyboris** [comment]
I'll be adding comments to keep track of things to do before v3 release. Others are welcome to discuss anything here too.

- https://github.com/whyboris/Video-Hub-App/issues/454#issuecomment-647819516 - make sure `Default` sort makes sense (with the new indexing system?) and when re-opening the app, the previous sort order shows up in the dropdown 😅

**Comment by TheTacoScott** [comment]
I think there is wisdom considering these (in whole or in part) for consideration in v3.x

https://github.com/whyboris/Video-Hub-App/issues/474
https://github.com/whyboris/Video-Hub-App/issues/475
https://github.com/whyboris/Video-Hub-App/issues/476

**Comment by whyboris** [comment]
Thank you @TheTacoScott -- I looked over these, but am not yet sold on the benefits (especially considering the immense cost in time of development). Please feel free to let me know more reasons in favor of any of the proposals in their respective _Issue_ pages 👍

**Comment by whyboris** [comment]
I renamed `master` to `main` and merged in #443 😅 maybe the largest PR ever 🎉 

Now it's time to clean things up, add a few minor features (closing the various small issues remaining) and get 3.0.0 released 🎉 🤞 

There's still leftover things to do -- at least a month or two of work:
- [ ] implement Cal's [blocks](https://github.com/whyboris/Video-Hub-App/pull/432#issuecomment-634632286) idea
- [ ] address Cal's [backlog](https://github.com/whyboris/Video-Hub-App/pull/383#issuecomment-632051168)

**Comment by whyboris** [comment]
Also, the release is *blocked* by a problem with scanning remote directories:
https://github.com/paulmillr/chokidar/issues/895 😓 
I've identified the problem in `chokidar` and proposed a solution -- I hope it will get resolved 🤞

**Comment by whyboris** [comment]
I have a PR that may fix the problem with network folders 🤞 https://github.com/paulmillr/chokidar/pull/1025

**Comment by whyboris** [comment]
Reminder to self:
- [ ] The sort filter shows "Default" on start-up even though it might be displaying a different sort order 😅 - must fix ⚠️

**Comment by whyboris** [comment]
Possible *TODO*: https://github.com/whyboris/Video-Hub-App/issues/355#issuecomment-671490094 <-- some items on this list

**Comment by orkomlosh** [comment]
> Possible _TODO_: [#355 (comment)](https://github.com/whyboris/Video-Hub-App/issues/355#issuecomment-671490094) <-- some items on this list

**so we won't get confused this item was already done:**
_The HTML & CSS for the layout is rather hack-y, but it works well enough for now. One UI (user interface) problem I'm facing is the import indicator (doughnut progress bar on top-right). It stays even when the top ribbon (with folder & file name) gets collapsed, thus overlapping with the settings button (the gear). I'm unsure how to handle this with the UI 🤔_

**Comment by whyboris** [comment]
Thanks for that fix again @orkomlosh 😁 -- I'm adding a short summary of https://github.com/whyboris/Video-Hub-App/issues/355#issuecomment-671490094

- [ ] move the ImageElement[] to a dedicated service
- [ ] update children components to update a video properties, no need to emit and communicate back to `home.component`
- [x] import indicator (doughnut progress bar on top-right) should hide when top bar is collapsed (fix by @orkomlosh 🎉 #498)
- [ ] #420 cleaning up the click-emissions

**Comment by whyboris** [comment]
Thanks @lighthunt 👍 I've been thinking about the "root" folders when in "show folders" view too.

I'm unsure about my final decision (at least for now, prior to releasing `3.0.0`). At the moment it's easiest to not change anything - the code works 🤷 but I agree that it would make conceptual sense to see the root folders first.

There _is_ a nice aspect to not having root folders -- if you have two hard drives with similar folders, I believe the folders will be combined. So `C:/movies/comedies` and `D:/movies/comedies` will show up as a single folder "comedies" and show contents of both 🤔 

I'll have to look at the code and see if it's easy to implement the change. If it's super easy, I might even have a toggle button in the settings. Most likely though, the code is complicated and won't be easy to change. It took me at least a day of work to get the algorithm right: https://github.com/whyboris/Video-Hub-App/blob/main/src/app/pipes/folder-view.pipe.ts#L101 😅 

We'll see - and thank you for the comment. Please feel free to share more thoughts on this or anything 😁

**Comment by lighthunt** [comment]
@whyboris "root" folders view -> I see what do you mean with the combination...
I guess if both approaches sounds reasonable and depends on data, a toggle for the user to choose would be the right thing to do (if the time/priority allows).

I think the motivation for seeing root folders from my POV (apart from being more logical in the way how my data are structured) was to be able to distinguish and browse only folders that are online/mounted .. I made a separate feature request for your consideration here #508

**Comment by orkomlosh** [comment]
>  move the ImageElement[] to a dedicated service
> update children components to update a video properties, no need to emit and communicate back to home.component
i think i covered most of it in my 3 recent PR's.
let me know if you think it's not cover yet

**Comment by whyboris** [comment]
I'm thinking of just releasing version `3.0.0` in the next month. All that's left is checking for _extraction_ and _watch folder_ bugs 😅 and it's ready to go 🚀 

I'll need to think through how/whether it should be possible to cancel / stop the `chokidar` scan (currently no - but there is an indication that the scan is happening). Perhaps I should prevent some app interactions while `chokidar` is running 🤔 -- stuff to think about.

**Comment by kevinseelbach** [comment]
@whyboris Would it be a good idea to add a keyboard shortcut "adding" feature where, say you right click an action button, for example the "shuffle videos" icon in the menu/navbar, and a context menu comes up allowing you to assign a keyboard shortcut to the action? Does that make sense?

**Comment by whyboris** [comment]
@kevinseelbach -- this seems like a cool feature, but feels like it would take a lot of effort to write / add. The code addition wouldn't be trivial, and the UI would be a challenge.

ps - For many features, one of the big challenges is the UI (user interface) -- communicating clearly to users what is possible ("affordance") and how it can be done, preferably without resorting to large explanatory text. I'm not saying I've succeeded with this goal with all the features in my app - it's just something I'm striving towards 😅

**Comment by whyboris** [comment]
Thank you to @martincaron for the excellent investigation of the various combinations of searches across tags, folders, files, etc:

https://github.com/whyboris/Video-Hub-App/issues/403#issuecomment-629664020

Even though I closed that issue, I think it's worth having a discussion about whether to change anything going forward. 

I suspect we'll leave everything as is until after `3.0.0` is released (omg I've been trying to get this released for so long 😓 )

@martincaron -- feel free to chime in here, or if you prefer we could start another _Issue_ dedicated to what you're proposing 🙇

**Comment by whyboris** [comment]
🤞 hoping to release `3.0.0` before _Thanksgiving_ 😁 

- [ ] make sure `demo` is limited to 50 videos without bugging out 👌

**Comment by whyboris** [comment]
Closing and transferring the remaining issues to #574 ✅
