### ISSUE TITLE
Horizontal filmstrip bug tracking

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#50]
The last PR #44 resulted in minor bugs when extracting videos, this PR does not fix them.

*Thumbnails **don't** show up* if:
- [x] the `vha` file is in the same directory as source files
- [x] the `vha` file has a space in its name
- [x] the screenshot size is 50px (and likely other sizes) - due to rounding error.
- [ ] Sometimes a slice of the next frame still appears in the thumbnail view
<img width="303" alt="screenshot 2018-12-29 at 15 40 32" src="https://user-images.githubusercontent.com/9119112/50539909-2c644900-0b80-11e9-938e-63b12560c46e.png">

- [x] The last frame is still often black in the film strip.
- [ ] Zooming out after scrolling to the end of the filmstrip prevents you from scrolling back when zoomed out!

This issue is meant to track various problems of this sort.

**Comment by cal2195** [comment]
Some other little issues:

1) Sometimes a slice of the next frame still appears in the thumbnail view
<img width="303" alt="screenshot 2018-12-29 at 15 40 32" src="https://user-images.githubusercontent.com/9119112/50539909-2c644900-0b80-11e9-938e-63b12560c46e.png">

2) The last frame is still often black in the film strip.

3) Zooming out after scrolling to the end of the filmstrip prevents you from scrolling back when zoomed out!

**Comment by cal2195** [comment]
Thumbnail preview and filmstrips aren't displaying for me on this MacBook - the video previews are though.

They're being generated, but the background-image: url isn't appearing in the final HTML. It worked last night on another system - could be some caching issue.

Still investigating!

**Comment by cal2195** [comment]
Ha, nevermind! Realised the issue is one you've already reported, although slightly expanded:

_Thumbnails **also don't** show up if:_
- The path to the `vha` file has a space in it!

I think you're first point is incorrect though - I have a vha in the same location as the source files and it works fine?

👍

**Comment by whyboris** [comment]
I'll look into this, probably close this issue and reopen a clean one with just the bugs that still persist 👍

**Comment by whyboris** [comment]
#131 <-- tracking for this particular issue 👌

**Comment by whyboris** [comment]
Closing -- we should open a new ticket in case something (re-)appears 😅
