### ISSUE TITLE
Boris - what I'm working on

### ISSUE THREAD

**Issue by whyboris** [whyboris/Video-Hub-App#99]
This is a small experiment to see if it's useful to have a public-facing "what I'm working on" on this list.

This is a place to be more transparent about what tasks I'm thinking of working on next. It's also a discussion - so please let me know if something should be a higher priority. I'm also happy to let anyone take over any task if it's of interest to them 🙇 

My aim is to always do all the code review before starting / resuming on my own coding.

Currently on my todo list in priority order (more will be added as I complete these):
- [x] _Details view_ - where tags (and more-detailed information about the video) will live #100 
- [x] Adding & filtering tags once the _Details view_ is merged to _master_ #53
- [x] Adding other fields (number of times viewed, star rating, date added) and associated filters 
- [x] Sorting by above-added filters #86 #80

**Comment by whyboris** [comment]
I'll keep both for some time and we'll see together which we like best 👍 

Even if an issue tracker / project board adds an extra step we need to do, there's some psychological satisfaction (at least I get) to putting check on checkboxes, or moving item along a Trello-like board 😅

**Comment by cal2195** [comment]
Haha, I know what you mean! 😂 

- [ ] Reply to Boris.

**Comment by whyboris** [comment]
Small additions:
- [ ] Add `width` and `height` fields to `ImageElement`, removing the hardcoded `ResolutionString` - meanwhile, also insert a temporary field for resolution (so as to compute it once: _on-file-open_, not every time: _on-view_). Also insert temporary field for resolution category (so the resolution filter service isn't crunching through _switch/case_ every time.
- [ ] Make the ⭐️ ⭐️ ⭐️ freshly-added star rating remain after scrolling away and scrolling back; Confirm that scrolling away and coming back doesn't remove the newly-added _tags_ (reconcile if/why behavior different)

**Comment by whyboris** [comment]
I'm giving `Projects` a try: https://github.com/whyboris/Video-Hub-App/projects/2

**Comment by whyboris** [comment]
I like _projects_ a lot to keep my _to do_ list organized. I'll use that instead of this issue.

I'll close this issue as soon as I implement the `number of times played` and `stars` sorting options.

**Comment by theotherp** [comment]
I'm not sure if this is the correct place to comment but I can't find the option to sort by anything but duration and size. I too would love to sort by recently added and file modification date.

**Comment by whyboris** [comment]
It's not obvious where the settings for that are. 
Please go to _settings_, click on the _Search settings_ tab, and scroll to the bottom.
The next-to-last section, titled "Show or hide various sorting options in the dropdown" allows you to enable other sort options besides the default few.

ps -- I'm thinking of including 'sort alphabetical' option before version 2 release 🙌

**Comment by theotherp** [comment]
Ohhh. Yes, that's indeed well hidden! Thanks.

**Comment by whyboris** [comment]
Thank you for the note -- I'll make sure to make features more visible (likely through a website `Features` section) :trollface:
